package com.accu_chek.solo_m.rcapp.data.nugendata;

import java.util.ArrayList;

import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;

import com.accu_chek.solo_m.rcapp.application.safety.CRCTool;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyChannel;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyString;
import com.accu_chek.solo_m.rcapp.application.util.CommonUtils;
import com.accu_chek.solo_m.rcapp.application.util.Debug;
import com.accu_chek.solo_m.rcapp.data.operationhandler.AbstractTable;
import com.accu_chek.solo_m.rcapp.data.operationhandler.IDBData;

public class EMWRLogTable extends AbstractTable
{
    // Table column name. This column value will be generated automatically by
    // Android.
    public static final String COLUMN_EMWR_ID = "emwr_id";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_SEGMENT_ID = "segment_id";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TIMESTAMP = "timestamp";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TIMESTAMP_DB = "timestamp_db";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_INSTANCE_ID = "instance_id";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_EMWR_TYPE = "emwr_type";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_EMWR_STATUS = "emwr_status";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_MESSAGE_NAME = "message_name";
    
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_COMMENT = "comment";
    
    // The ID of the current queried record generated by Android.
    private int mRecordId = -1;
    
    // Table column value encoded in JSON string type.
    private String mSegmentId = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mTimestamp = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mInstanceId = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mEMWRType = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mStatus = EMPTY_COLUMN_VALUE;
    
    // Table column value in String type.
    private String mMsgName = EMPTY_COLUMN_VALUE;
    
    // Table column value in String type.
    private String mComment = EMPTY_COLUMN_VALUE;
    
    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mRecordId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getRecordId()
    {
        SafetyChannel<Integer> channel = CommonUtils
                .getSafetyChannel(mRecordId);
        
        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mSegmentId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getSegmentId()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mSegmentId))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mSegmentId);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }
    
    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mTimestamp: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Long> getTimestamp()
    {
        SafetyChannel<Long> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mTimestamp))
        {
            long[] channelValue = DatabaseUtil
                    .restoreChannelLongValue(mTimestamp);
            channel = new SafetyChannel<Long>(channelValue[0], channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mInstanceId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getInstanceId()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mInstanceId))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mInstanceId);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mEMWRType: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getEMWRType()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mEMWRType))
        {
            int[] channelValue = DatabaseUtil.restoreChannelIntValue(mEMWRType);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mStatus: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getStatus()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mStatus))
        {
            int[] channelValue = DatabaseUtil.restoreChannelIntValue(mStatus);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return the column value.
     *            Range: valid object
     *            Unit: SafetyString
     *            Scaling: 1
     *            
     * @see mMsgName: Use this global variable for storing column value.
     * 
     */
    public SafetyString getMsgName()
    {
        SafetyString msgName = new SafetyString(mMsgName,
                CRCTool.generateCRC16(mMsgName.getBytes()));

        return msgName;
    }

    /**
     * Obtain column value.
     * 
     * @return the column value.
     *            Range: valid object
     *            Unit: SafetyString
     *            Scaling: 1
     *            
     * @see mComment: Use this global variable for storing column value.
     * 
     */
    public SafetyString getComment()
    {
        SafetyString comment = new SafetyString(mComment,
                CRCTool.generateCRC16(mComment.getBytes()));
        
        return comment;
    }

    /**
     * Obtain table column values from the values generated by the EMW service
     * to initialize the global variables for database operation (the insert or
     * update operation).
     * 
     * @param values : the values generated by the EMW service by the insert
     *            or update operation
     *            Range: valid object
     *            Unit: ContentValues
     *            Scaling: 1
     * 
     * @return None
     * 
     * @see mSegmentId: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mInstanceId: Use this global variable for storing column value.
     * @see mEMWRType: Use this global variable for storing column value.
     * @see mStatus: Use this global variable for storing column value.
     * @see mMsgName: Use this global variable for storing column value.
     * @see mComment: Use this global variable for storing column value.
     */
    @Override
    protected void getDataFromContentValue(ContentValues values)
    {
        CommonUtils.objectCheck(values);
        
        mSegmentId = DatabaseUtil.getStringValue(values, COLUMN_SEGMENT_ID,
                mSegmentId);
        mTimestamp = DatabaseUtil.getStringValue(values, COLUMN_TIMESTAMP,
                mTimestamp);
        mInstanceId = DatabaseUtil.getStringValue(values, COLUMN_INSTANCE_ID,
                mInstanceId);
        mEMWRType = DatabaseUtil.getStringValue(values, COLUMN_EMWR_TYPE,
                mEMWRType);
        mStatus = DatabaseUtil.getStringValue(values, COLUMN_EMWR_STATUS,
                mStatus);
        mMsgName = DatabaseUtil.getStringValue(values, COLUMN_MESSAGE_NAME,
                mMsgName);
        mComment = DatabaseUtil
                .getStringValue(values, COLUMN_COMMENT, mComment);

    }

    /**
     * Generate record CRC value according to the values of record data.
     * 
     * @return the generated CRC value
     *            Range: -2^31 to (2^31)-1
     *            Unit: int
     *            Scaling: 1
     * 
     * @see mSegmentId: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mInstanceId: Use this global variable for storing column value.
     * @see mEMWRType: Use this global variable for storing column value.
     * @see mStatus: Use this global variable for storing column value.
     * @see mMsgName: Use this global variable for storing column value.
     * @see mComment: Use this global variable for storing column value.
     */
    @Override
    public int generateCRC()
    {
        int nCRC = -1;
        ArrayList<String> list = new ArrayList<String>();

        list.add(mSegmentId);
        list.add(mTimestamp);
        list.add(mInstanceId);
        list.add(mEMWRType);
        list.add(mStatus);
        list.add(mMsgName);
        list.add(mComment);
        
        nCRC = DatabaseUtil.generateCRC(list);
        Debug.printI("QueryCommand", "genCRC() in EMWRLogTable. nCRC: "+ nCRC);

        return nCRC;
    }

    /**
     * Invoke this method to obtain the URI path of a certain table.
     * 
     * @return the URI reference of a certain table
     *            Range: valid object
     *            Unit: Uri
     *            Scaling: 1
     */
    @Override
    public Uri onUri()
    {
        return UrlType.emwrUri;
    }

    /**
     * Obtain the query record by cursor.
     * 
     * @param cursor : position to the entry of database table
     *            Range: valid object
     *            Unit: Cursor
     *            Scaling: 1
     * 
     * @return the query record
     *         Range: valid object
     *         Unit: IDBData
     *         Scaling: 1
     * 
     * @see mSegmentId: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mInstanceId: Use this global variable for storing column value.
     * @see mEMWRType: Use this global variable for storing column value.
     * @see mStatus: Use this global variable for storing column value.
     * @see mMsgName: Use this global variable for storing column value.
     * @see mComment: Use this global variable for storing column value.
     * @see mCRC: Use this global variable for storing calculated CRC value.
     */
    @Override
    public IDBData onQueryDataFromCursor(Cursor cursor)
    {
        EMWRLogTable model = null;
        
        CommonUtils.objectCheck(cursor);

        int recordIdIndex = cursor.getColumnIndex(COLUMN_EMWR_ID);
        int segmentidIndex = cursor.getColumnIndex(COLUMN_SEGMENT_ID);
        int timestampIndex = cursor.getColumnIndex(COLUMN_TIMESTAMP);
        int instanceIdIndex = cursor.getColumnIndex(COLUMN_INSTANCE_ID);
        int typeIndex = cursor.getColumnIndex(COLUMN_EMWR_TYPE);
        int statusIndex = cursor.getColumnIndex(COLUMN_EMWR_STATUS);
        int msgNameIndex = cursor.getColumnIndex(COLUMN_MESSAGE_NAME);
        int commentIndex = cursor.getColumnIndex(COLUMN_COMMENT);
        int crcIndex = cursor.getColumnIndex(COLUMN_CRC);

        model = new EMWRLogTable();

        model.mRecordId = cursor.getInt(recordIdIndex);
        model.mSegmentId = DatabaseUtil.getStringValue(cursor, segmentidIndex);
        model.mTimestamp = DatabaseUtil.getStringValue(cursor, timestampIndex);
        model.mInstanceId = DatabaseUtil
                .getStringValue(cursor, instanceIdIndex);
        model.mEMWRType = DatabaseUtil.getStringValue(cursor, typeIndex);
        model.mStatus = DatabaseUtil.getStringValue(cursor, statusIndex);
        model.mMsgName = DatabaseUtil.getStringValue(cursor, msgNameIndex);
        model.mComment = DatabaseUtil.getStringValue(cursor, commentIndex);
        model.setCRC(DatabaseUtil.getIntValue(cursor, crcIndex));
        
        return model;

    }

    /**
     * Obtain the primary key name of a certain table for the update operation.
     * 
     * @return the primary key name of a certain table
     *         Range: valid object
     *         Unit: String
     *         Scaling: 1
     */
    @Override
    public String getPrimaryKeyName()
    {
        return EMWRLogTable.COLUMN_EMWR_ID;
    }

    /**
     * Obtain the name of a certain table for the database operation.
     * 
     * @return the name of a certain table
     *         Range: valid object
     *         Unit: String
     *         Scaling: 1
     */
    @Override
    protected String getTableName()
    {
        return DBHelper.EMWR_LOG_TABLE;
    }

}
