package com.accu_chek.solo_m.rcapp.data.nugendata;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;
import android.util.Log;

import com.accu_chek.solo_m.rcapp.application.common.NugenFrameworkConstants.CommonConstants;
import com.accu_chek.solo_m.rcapp.application.safety.CRCTool;
import com.accu_chek.solo_m.rcapp.application.safety.SFloat;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyChannel;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyFloat;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyString;
import com.accu_chek.solo_m.rcapp.application.util.CommonUtils;
import com.accu_chek.solo_m.rcapp.application.util.Debug;
import com.accu_chek.solo_m.rcapp.data.operationhandler.AbstractTable;
import com.accu_chek.solo_m.rcapp.data.operationhandler.IDBData;

public class HistoryDataTable extends AbstractTable
{
    // Table column name. This column value will be generated automatically by
    // Android.
    public static final String COLUMN_HISTORYDATA_ID = "historydata_id";

    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_TYPE = "event_type";

    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_SEQUENCE_NUM = "sequence_num";

    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_TIME_OFFSET = "time_offset";

    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_DATA = "event_data";

    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_ID = "event_id";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_TITLE = "event_title";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_DETAIL = "event_detail";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BOLUSTYPE = "event_bolustype";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BOLUSDOSE = "event_bolusdose";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BOLUSDURATION = "event_bolusduration";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BASALBRPPERCENTAGE = "event_basalbrppercentage";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BASALBRPDURATION = "event_basalbrpduration";
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_EVENT_BASALTBRDOSE = "event_basaltbrdose";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TIMESTAMP = "timestamp";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TIMESTAMP_DB = "timestamp_db";
    
    // Table column name. This column value can be null when inserting.
    public static final String COLUMN_PUMP_ID = "pump_id";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_SEGMENT_ID = "segment_id";

    // The ID of the current queried record generated by Android.
    private int mRecordId = -1;
    
    // Table column value encoded in JSON string type.
    private String mEventType = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mSequenceNumber = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mTimeOffset = EMPTY_COLUMN_VALUE;
    
    // Table column value in String type.
    private String mEventData = EMPTY_COLUMN_VALUE;
    
    // Table column value in String type.
    private String mEventId = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventTitle = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventDetail = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBolustype = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBolusdose = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBolusduration = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBasalbrppercentage = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBasalduration = EMPTY_COLUMN_VALUE;
    // Table column value in String type.
    private String mEventBasaltbrdose = EMPTY_COLUMN_VALUE;
    
    
    // Table column value encoded in JSON string type.
    private String mTimestamp = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mPumpId = EMPTY_COLUMN_VALUE;
    
    // Table column value encoded in JSON string type.
    private String mSegmentId = EMPTY_COLUMN_VALUE;

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mRecordId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getRecordId()
    {
        SafetyChannel<Integer> channel = CommonUtils
                .getSafetyChannel(mRecordId);

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mEventType: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getEventType()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mEventType))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mEventType);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mSequenceNumber: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getSequenceNumber()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mSequenceNumber))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mSequenceNumber);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mTimeOffset: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getTimeOffset()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mTimeOffset))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mTimeOffset);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return The string wrapped in SafetyString type.
     *         Range: valid object
     *         Unit: SafetyString
     *         Scaling: 1
     * 
     * @see mEventData: Use this global variable for storing column value.
     * 
     */
    public SafetyString getEventData()
    {
        SafetyString sResult = new SafetyString(mEventData,
                CRCTool.generateCRC16(mEventData.getBytes()));

        return sResult;
    }

    
    public SafetyString getEventId()
    {
        SafetyString sResult = new SafetyString(mEventId,CRCTool.generateCRC16(mEventId.getBytes()));
        return sResult;
    }

    public SafetyString getEventTitle()
    {
        SafetyString sResult = new SafetyString(mEventTitle,CRCTool.generateCRC16(mEventTitle.getBytes()));
        return sResult;
    }
    public SafetyString getEventDetail()
    {
        SafetyString sResult = new SafetyString(mEventDetail,CRCTool.generateCRC16(mEventDetail.getBytes()));
        return sResult;
    }
    public SafetyString getEventBolustype()
    {
        SafetyString sResult = new SafetyString(mEventBolustype,CRCTool.generateCRC16(mEventBolustype.getBytes()));
        return sResult;
    }
    
    public SafetyChannel<Integer> getEventBolusdose()
    {
        int[] channelValue = null;
        SafetyChannel<Integer> channel = null;

        if (!mEventBolusdose.isEmpty())
        {
            channelValue = DatabaseUtil.restoreChannelIntValue(mEventBolusdose);
        }
        // If the Meal Time code is empty string then return default (No entry)
        else
        {
            channelValue = new int[2];
            channelValue[0] = CommonUtils
                    .encodeCH1Value(CommonConstants.MEAL_TIME_NO_ENTRY);
            channelValue[1] = CommonUtils
                    .encodeCH2Value(CommonConstants.MEAL_TIME_NO_ENTRY);
        }
        channel = new SafetyChannel<Integer>(channelValue[0], channelValue[1]);

        return channel;
        
    }
    public SafetyChannel<Integer> getEventBolusduration()
    {
    	
        int[] channelValue = null;
        SafetyChannel<Integer> channel = null;

        if (!mEventBolusdose.isEmpty())
        {
            channelValue = DatabaseUtil.restoreChannelIntValue(mEventBolusdose);
        }
        // If the Meal Time code is empty string then return default (No entry)
        else
        {
            channelValue = new int[2];
            channelValue[0] = CommonUtils
                    .encodeCH1Value(CommonConstants.MEAL_TIME_NO_ENTRY);
            channelValue[1] = CommonUtils
                    .encodeCH2Value(CommonConstants.MEAL_TIME_NO_ENTRY);
        }
        channel = new SafetyChannel<Integer>(channelValue[0], channelValue[1]);

        return channel;
    	
    }
    public SafetyString getEventBasalbrppercentage()
    {
        SafetyString sResult = new SafetyString(mEventBasalbrppercentage,CRCTool.generateCRC16(mEventBasalbrppercentage.getBytes()));
        return sResult;
    }
    public SafetyString getEventBasalduration()
    {
        SafetyString sResult = new SafetyString(mEventBasalduration,CRCTool.generateCRC16(mEventBasalduration.getBytes()));
        return sResult;
    }
    
    public SafetyChannel<Integer> getEventBasaltbrdose()
    {
        int[] channelValue = null;
        SafetyChannel<Integer> channel = null;

        if (!mEventBasaltbrdose.isEmpty())
        {
            channelValue = DatabaseUtil.restoreChannelIntValue(mEventBasaltbrdose);
        }
        // If the Meal Time code is empty string then return default (No entry)
        else
        {
            channelValue = new int[2];
            channelValue[0] = CommonUtils
                    .encodeCH1Value(CommonConstants.MEAL_TIME_NO_ENTRY);
            channelValue[1] = CommonUtils
                    .encodeCH2Value(CommonConstants.MEAL_TIME_NO_ENTRY);
        }
        channel = new SafetyChannel<Integer>(channelValue[0], channelValue[1]);
        return channel;
    }
    
    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mTimestamp: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Long> getTimestamp()
    {
        SafetyChannel<Long> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mTimestamp))
        {
            long[] channelValue = DatabaseUtil
                    .restoreChannelLongValue(mTimestamp);
            channel = new SafetyChannel<Long>(channelValue[0], channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mPumpId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getPumpId()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mPumpId))
        {
            int[] channelValue = DatabaseUtil.restoreChannelIntValue(mPumpId);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain column value.
     * 
     * @return Returns an object which stores the values of channel 1 and
     *         channel 2.
     *         Range: valid object
     *         Unit: SafetyChannel
     *         Scaling: 1
     * 
     * @see mSegmentId: Use this global variable for storing column value.
     * 
     */
    public SafetyChannel<Integer> getSegmentId()
    {
        SafetyChannel<Integer> channel = null;

        if (!EMPTY_COLUMN_VALUE.equals(mSegmentId))
        {
            int[] channelValue = DatabaseUtil
                    .restoreChannelIntValue(mSegmentId);
            channel = new SafetyChannel<Integer>(channelValue[0],
                    channelValue[1]);
        }

        return channel;
    }

    /**
     * Obtain table column values from the values generated by the pump to
     * initialize the global variables for database operation (the insert or
     * update operation).
     * 
     * @param values : the values generated by the pump by the insert or update
     *            operation
     *            Range: valid object
     *            Unit: ContentValues
     *            Scaling: 1
     * 
     * @return None
     * 
     * @see mEventType: Use this global variable for storing column value.
     * @see mSequenceNumber: Use this global variable for storing column value.
     * @see mTimeOffset: Use this global variable for storing column value.
     * @see mEventData: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mPumpId: Use this global variable for storing column value.
     * @see mSegmentId: Use this global variable for storing column value.
     */
    @Override
    protected void getDataFromContentValue(ContentValues values)
    {
        CommonUtils.objectCheck(values);

        mEventType = DatabaseUtil.getStringValue(values, COLUMN_EVENT_TYPE,
                mEventType);
        mSequenceNumber = DatabaseUtil.getStringValue(values,
                COLUMN_SEQUENCE_NUM, mSequenceNumber);
        mTimeOffset = DatabaseUtil.getStringValue(values, COLUMN_TIME_OFFSET,
                mTimeOffset);
        mEventData = DatabaseUtil.getStringValue(values, COLUMN_EVENT_DATA,
                mEventData);
        
        
        mEventId = DatabaseUtil.getStringValue(values, COLUMN_EVENT_ID, mEventId);
        mEventTitle = DatabaseUtil.getStringValue(values, COLUMN_EVENT_TITLE, mEventTitle);
        mEventDetail = DatabaseUtil.getStringValue(values, COLUMN_EVENT_DETAIL, mEventDetail);
        mEventBolustype = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BOLUSTYPE, mEventBolustype);
        mEventBolusdose = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BOLUSDOSE, mEventBolusdose);
        mEventBolusduration = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BOLUSDURATION, mEventBolusduration);
        mEventBasalbrppercentage = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BASALBRPPERCENTAGE, mEventBasalbrppercentage);
        mEventBasalduration = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BASALBRPDURATION, mEventBasalduration);
        mEventBasaltbrdose = DatabaseUtil.getStringValue(values, COLUMN_EVENT_BASALTBRDOSE, mEventBasaltbrdose);
        
        
        mTimestamp = DatabaseUtil.getStringValue(values, COLUMN_TIMESTAMP,
                mTimestamp);
        mPumpId = DatabaseUtil.getStringValue(values, COLUMN_PUMP_ID, mPumpId);
        mSegmentId = DatabaseUtil.getStringValue(values, COLUMN_SEGMENT_ID,
                mSegmentId);
    }

    /**
     * Generate record CRC value according to the values of record data.
     * 
     * @return the generated CRC value
     *         Range: -2^31 to (2^31)-1
     *         Unit: int
     *         Scaling: 1
     * 
     * @see mEventType: Use this global variable for storing column value.
     * @see mSequenceNumber: Use this global variable for storing column value.
     * @see mTimeOffset: Use this global variable for storing column value.
     * @see mEventData: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mPumpId: Use this global variable for storing column value.
     * @see mSegmentId: Use this global variable for storing column value.
     */
    @Override
    public int generateCRC()
    {
        int nCRC = -1;
        ArrayList<String> list = new ArrayList<String>();

        list.add(mEventType);
        list.add(mSequenceNumber);
        list.add(mTimeOffset);
        list.add(mEventData);
        list.add(mTimestamp);
        list.add(mPumpId);
        list.add(mSegmentId);

        nCRC = DatabaseUtil.generateCRC(list);
        Debug.printI("QueryCommand", "genCRC() in HistoryDataTable. nCRC: "
                + nCRC);

        return nCRC;
    }

    /**
     * Invoke this method to obtain the URI path of a certain table.
     * 
     * @return the URI reference of a certain table
     *         Range: valid object
     *         Unit: Uri
     *         Scaling: 1
     */
    @Override
    public Uri onUri()
    {
        return UrlType.histotydataUri;
    }

    /**
     * Obtain the query record by cursor.
     * 
     * @param cursor : position to the entry of database table
     *            Range: valid object
     *            Unit: Cursor
     *            Scaling: 1
     * 
     * @return the query record
     *         Range: valid object
     *         Unit: IDBData
     *         Scaling: 1
     * 
     * @see mEventType: Use this global variable for storing column value.
     * @see mSequenceNumber: Use this global variable for storing column value.
     * @see mTimeOffset: Use this global variable for storing column value.
     * @see mEventData: Use this global variable for storing column value.
     * @see mTimestamp: Use this global variable for storing column value.
     * @see mPumpId: Use this global variable for storing column value.
     * @see mSegmentId: Use this global variable for storing column value.
     * @see mCRC: Use this global variable for storing calculated CRC value.
     */
    @Override
    public IDBData onQueryDataFromCursor(Cursor cursor)
    {
        HistoryDataTable model = null;

        CommonUtils.objectCheck(cursor);

        int recordIdIndex = cursor.getColumnIndex(COLUMN_HISTORYDATA_ID);
        int eventTypeIndex = cursor.getColumnIndex(COLUMN_EVENT_TYPE);
        int sequenceNumberIndex = cursor.getColumnIndex(COLUMN_SEQUENCE_NUM);
        int timeOffsetIndex = cursor.getColumnIndex(COLUMN_TIME_OFFSET);
        int eventDataIndex = cursor.getColumnIndex(COLUMN_EVENT_DATA);
        
        
        
        int eventIdIndex = cursor.getColumnIndex(COLUMN_EVENT_ID);
        int eventTitleIndex = cursor.getColumnIndex(COLUMN_EVENT_TITLE);
        int eventDetailIndex = cursor.getColumnIndex(COLUMN_EVENT_DETAIL);
        int eventBolustypeIndex = cursor.getColumnIndex(COLUMN_EVENT_BOLUSTYPE);
        int eventBolusdoseIndex = cursor.getColumnIndex(COLUMN_EVENT_BOLUSDOSE);
        int eventBolusdurationIndex = cursor.getColumnIndex(COLUMN_EVENT_BOLUSDURATION);
        int eventBasalbrppercentageIndex = cursor.getColumnIndex(COLUMN_EVENT_BASALBRPPERCENTAGE);
        int eventBasaldurationIndex = cursor.getColumnIndex(COLUMN_EVENT_BASALBRPDURATION);
        int eventBasaltbrdoseIndex = cursor.getColumnIndex(COLUMN_EVENT_BASALTBRDOSE);
        
        int timestampIndex = cursor.getColumnIndex(COLUMN_TIMESTAMP);
        int pumpIdIndex = cursor.getColumnIndex(COLUMN_PUMP_ID);
        int segmentIdIndex = cursor.getColumnIndex(COLUMN_SEGMENT_ID);
        int crcIndex = cursor.getColumnIndex(COLUMN_CRC);

        model = new HistoryDataTable();

        model.mRecordId = cursor.getInt(recordIdIndex);
        model.mEventType = DatabaseUtil.getStringValue(cursor, eventTypeIndex);
        model.mSequenceNumber = DatabaseUtil.getStringValue(cursor,
                sequenceNumberIndex);
        model.mTimeOffset = DatabaseUtil
                .getStringValue(cursor, timeOffsetIndex);
        model.mEventData = DatabaseUtil.getStringValue(cursor, eventDataIndex);
        
        model.mEventId = DatabaseUtil.getStringValue(cursor, eventIdIndex);
        model.mEventTitle = DatabaseUtil.getStringValue(cursor, eventTitleIndex);
        model.mEventDetail = DatabaseUtil.getStringValue(cursor, eventDetailIndex);
        model.mEventBolustype = DatabaseUtil.getStringValue(cursor, eventBolustypeIndex);
        model.mEventBolusdose = DatabaseUtil.getStringValue(cursor, eventBolusdoseIndex);
        model.mEventBolusduration = DatabaseUtil.getStringValue(cursor, eventBolusdurationIndex);
        model.mEventBasalbrppercentage = DatabaseUtil.getStringValue(cursor, eventBasalbrppercentageIndex);
        model.mEventBasalduration = DatabaseUtil.getStringValue(cursor, eventBasaldurationIndex);
        model.mEventBasaltbrdose = DatabaseUtil.getStringValue(cursor, eventBasaltbrdoseIndex);
        
        model.mTimestamp = DatabaseUtil.getStringValue(cursor, timestampIndex);
        model.mPumpId = DatabaseUtil.getStringValue(cursor, pumpIdIndex);
        model.mSegmentId = DatabaseUtil.getStringValue(cursor, segmentIdIndex);
        model.setCRC(DatabaseUtil.getIntValue(cursor, crcIndex));
        return model;

    }

    /**
     * Obtain the primary key name of a certain table for the update operation.
     * 
     * @return the primary key name of a certain table
     *         Range: valid object
     *         Unit: String
     *         Scaling: 1
     */
    @Override
    public String getPrimaryKeyName()
    {
        return HistoryDataTable.COLUMN_HISTORYDATA_ID;
    }

    /**
     * Obtain the name of a certain table for the database operation.
     * 
     * @return the name of a certain table
     *         Range: valid object
     *         Unit: String
     *         Scaling: 1
     */
    @Override
    protected String getTableName()
    {
        return DBHelper.HISTORYDATA_TABLE;
    }

    

    
    public EventType_0F EventType0F = new EventType_0F();
    public String SimulateEventType_0F( int Recording_Reason , long timestamp , int Time_Zone , int DST_Offset )
    {
    	return EventType0F.encode(Recording_Reason , timestamp , Time_Zone , DST_Offset);
    }
    public EventType_0F get_EventType_0F()
    {
    	SafetyString eventdata = getEventData();
    	EventType0F.decode(eventdata.getString());
    	return EventType0F;
    }
    
    public EventType_5A EventType5A = new EventType_5A();  
    public String SimulateEventType_5A( int Bolus_ID , int Bolus_Type , float Programmed_Bolus_Fast_Amount , float Programmed_Bolus_Extended_Amount , int Programmed_Bolus_Duration )
    {
    	return EventType5A.encode(Bolus_ID, Bolus_Type, Programmed_Bolus_Fast_Amount, Programmed_Bolus_Extended_Amount, Programmed_Bolus_Duration);
    }
    public EventType_5A get_EventType_5A()
    {
    	SafetyString eventdata = getEventData();
    	EventType5A.decode(eventdata.getString());
    	return EventType5A;
    }
    
    public EventType_66 EventType66 = new EventType_66();
    public String SimulateEventType_66( int Flags , int Bolus_Delay_Time , int Bolus_Template_Number , int Bolus_Activation_Type )
    {
    	return EventType66.encode(Flags , Bolus_Delay_Time , Bolus_Template_Number , Bolus_Activation_Type);
    }
    public EventType_66 get_EventType_66()
    {
    	SafetyString eventdata = getEventData();
    	EventType66.decode(eventdata.getString());
    	return EventType66;
    }
    
    public EventType_69 EventType69 = new EventType_69();
    public String SimulateEventType_69( int Bolus_ID , int Bolus_Type , float Delivered_Bolus_Fast_Amount , float Delivered_Bolus_Extended_Amount , int Effective_Bolus_Duration )
    {
    	return EventType69.encode(Bolus_ID , Bolus_Type , Delivered_Bolus_Fast_Amount , Delivered_Bolus_Extended_Amount , Effective_Bolus_Duration);
    }
    public EventType_69 get_EventType_69()
    {
    	SafetyString eventdata = getEventData();
    	EventType69.decode(eventdata.getString());
    	return EventType69;
    }
    
    public EventType_96 EventType96 = new EventType_96();
    public String SimulateEventType_96( int Flags , int Bolus_Start_Time_Offset , int Bolus_Activation_Type )
    {
    	return EventType96.encode(Flags , Bolus_Start_Time_Offset , Bolus_Activation_Type);
    }
    public EventType_96 get_EventType_96()
    {
    	SafetyString eventdata = getEventData();
    	EventType96.decode(eventdata.getString());
    	return EventType96;
    }
    
    public EventType_30C EventType30C = new EventType_30C();
    public String SimulateEventType_30C( int Operational_State )
    {
    	return EventType30C.encode(Operational_State);
    }
    public EventType_30C get_EventType_30C()
    {
    	SafetyString eventdata = getEventData();
    	EventType30C.decode(eventdata.getString());
    	return EventType30C;
    }
    

    /*
    0x000F
    Table 3 87<<IDD History Data>> Reference Time Event, event data definition
    Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order	SIG assigned Number UUID
    Recording Reason	Mandatory	enum of uint8	1	none	N/A	N/A 
    Date Time	Mandatory	various	7	date time record	LSO¡KMSO	0x2A08
    Time Zone	Mandatory	sint8	1	none	N/A	0x2A0E 
    DST Offset	Mandatory	uint8	1	none	N/A	0x2A0F 
*/        
    public class EventType_0F{
    	public int getRecording_Reason() {
			return Recording_Reason;
		}
		public int getDate_Time() {
			return Date_Time;
		}
		public long getTimestamp() {
			return timestamp;
		}
		int Recording_Reason= 0;
    	int Date_Time= 0;
    	int Time_Zone = 0;
    	int DST_Offset = 0;
    	long timestamp = 0;
    	
    	
    	public String encode(int Recording_Reason , long timestamp , int Time_Zone , int DST_Offset)
    	{
    		this.Recording_Reason = Recording_Reason;
    		this.timestamp = timestamp;
        	this.Time_Zone = Time_Zone;
        	this.DST_Offset = DST_Offset;
    		byte[] result = new byte[10];
    		result[0] = (byte) ((Recording_Reason & 0x000000FF) >> 0);
/*
Year	Mandatory	uint16	1582	9999	[Year]	0 = "year not known"
Month	Mandatory	enum of uint8	0	12	[Month]	enumeration see section 4.1.5
Day	Mandatory	uint8	1	31	[Day]	0 = "day not known"
Hours	Mandatory	uint8	0	23	[Hours]	none
Minutes	Mandatory	uint8	0	59	[Minutes]	none
Seconds	Mandatory	uint8	0	59	[Seconds]	none
Table 4 1	Date and Time value as specified by the Bluetooth SIG
*/
    		Calendar cal = Calendar.getInstance();
    		cal.setTimeInMillis(timestamp);
    		result[1] = (byte) ((cal.get(Calendar.YEAR) & 0x000000FF) >> 0);
    		result[2] = (byte) ((cal.get(Calendar.YEAR) & 0x0000FF00) >> 8);
    		//month
    		result[3] = (byte) ((cal.get(Calendar.MONTH)+1) & 0x000000FF);
    		//day
    		result[4] = (byte) (cal.get(Calendar.DAY_OF_MONTH) & 0x000000FF);
    		//hours
    		result[5] = (byte) (cal.get(Calendar.HOUR) & 0x000000FF);
    		//minutes
    		result[6] = (byte) (cal.get(Calendar.MINUTE) & 0x000000FF);
    		//seconds
    		result[7] = (byte) (cal.get(Calendar.SECOND) & 0x000000FF);
    		
    		
    		result[8] = (byte) ((Time_Zone & 0x000000FF) >> 0);
    		result[9] = (byte) ((DST_Offset & 0x000000FF) >> 0);
    		//return getHex( result );
    		
    		String d = getHex( result );
    		Log.i("kayjean" , "EventType_0F encode " + d );
    		decode(d);
    		return d;
    	}

    	public void decode( String s )
    	{
    		Log.i("kayjean" , "EventType_0F decode " + s );
    		byte[] ret = hexStringToByteArray( s );
    		
    		this.Recording_Reason = ret[0] & 0xFF;
    		Log.i("kayjean" , "EventType_0F Recording_Reason " + this.Recording_Reason );
    		
    		int year  = ret[1] & 0xFF | (ret[2] & 0xFF) << 8;
    		int month = ret[3] & 0xFF;
    		int day =   ret[4] & 0xFF;
    		int hour =  ret[5] & 0xFF;
    		int minute = ret[6] & 0xFF;
    		int second = ret[7] & 0xFF;

    		
    		Calendar cal = GregorianCalendar.getInstance();
    		cal.set(Calendar.DAY_OF_MONTH, day);// I might have the wrong Calendar constant...
    		cal.set(Calendar.MONTH, month-1);// -1 as month is zero-based
    		cal.set(Calendar.YEAR, year);
    		cal.set(Calendar.HOUR, hour);
    		cal.set(Calendar.MINUTE, minute);
    		cal.set(Calendar.SECOND, second);
    		Timestamp t = new Timestamp(cal.getTimeInMillis());
    		this.timestamp = t.getTime();

    		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    		String str = df.format( t );
    		Log.i("kayjean" , "EventType_0F timestamp " + str );
    		
    		this.Time_Zone = ret[8] & 0xFF;
    		this.DST_Offset = ret[9] & 0xFF;
    		return;
    	}
    }
    
    
    
    public class EventType_5A{
    	public int getBolus_ID() {
			return Bolus_ID;
		}

		public int getBolus_Type() {
			return Bolus_Type;
		}

		public float getProgrammed_Bolus_Fast_Amount() {
			return Programmed_Bolus_Fast_Amount;
		}

		public float getProgrammed_Bolus_Extended_Amount() {
			return Programmed_Bolus_Extended_Amount;
		}

		public int getProgrammed_Bolus_Duration() {
			return Programmed_Bolus_Duration;
		}

		int Bolus_ID = 0;
    	int Bolus_Type = 0;
    	float Programmed_Bolus_Fast_Amount = 0;
    	float Programmed_Bolus_Extended_Amount = 0;
    	int Programmed_Bolus_Duration = 0;

/*    	
    	Table 3 89<<IDD History Data>>, Bolus Programmed Part 1 of 2, event data definition
    	Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order
    	Bolus ID	Mandatory	uint16	2	none	LSO¡KMSO 
    	Bolus Type	Mandatory	enum of uint8	1	none	N/A 
    	Programmed Bolus Fast Amount	Mandatory	SFLOAT	2	IU	LSO¡KMSO 
    	Programmed Bolus Extended Amount	Mandatory	SFLOAT	2	IU	LSO¡KMSO 
    	Programmed Bolus Duration	Mandatory	uint16	2	minutes	LSO¡KMSO 
*/

    	public String encode( int Bolus_ID , int Bolus_Type , float Programmed_Bolus_Fast_Amount , float Programmed_Bolus_Extended_Amount , int Programmed_Bolus_Duration  )
    	{
    		this.Bolus_ID = Bolus_ID;
        	this.Bolus_Type = Bolus_Type;
        	this.Programmed_Bolus_Fast_Amount = Programmed_Bolus_Fast_Amount;
        	this.Programmed_Bolus_Extended_Amount = Programmed_Bolus_Extended_Amount;
        	this.Programmed_Bolus_Duration = Programmed_Bolus_Duration;
    		byte[] result = new byte[9];
    		//result[0] = (byte) ((data & 0xFF000000) >> 24);
    		//result[1] = (byte) ((data & 0x00FF0000) >> 16);
    		//result[2] = (byte) ((data & 0x0000FF00) >> 8);
    		//result[3] = (byte) ((data & 0x000000FF) >> 0);
    		result[0] = (byte) ((Bolus_ID & 0x000000FF) >> 0);
    		result[1] = (byte) ((Bolus_ID & 0x0000FF00) >> 8);
    		
    		result[2] = (byte) ((Bolus_Type & 0x000000FF) >> 0);

    		short s1 = ToSFloat( (double)Programmed_Bolus_Fast_Amount );
    		result[4] = (byte)((s1 >> 8) & 0xff);
    		result[3] = (byte)(s1 & 0xff);    		

    		short s2 = ToSFloat( (double)Programmed_Bolus_Extended_Amount );
    		result[6] = (byte)((s2 >> 8) & 0xff);
    		result[5] = (byte)(s2 & 0xff);
    		
    		result[7] = (byte) ((Programmed_Bolus_Duration & 0x000000FF) >> 0);
    		result[8] = (byte) ((Programmed_Bolus_Duration & 0x0000FF00) >> 8);
    		
    		decode(getHex( result ));
    		return getHex( result );
    	}

    	public void decode( String s )
    	{
    		Log.i("kayjean" , "EventType_5A decode " + s );
    		byte[] ret = hexStringToByteArray( s );
    		this.Bolus_ID = ret[0] & 0xFF | (ret[1] & 0xFF) << 8;
    		this.Bolus_Type = ret[2] & 0xFF;
    		
    		short s1 = (short)(ret[3] & 0xFF | (ret[4] & 0xFF) << 8);
    		this.Programmed_Bolus_Fast_Amount = (float)ToValue( s1 );

    		short s2 = (short)(ret[5] & 0xFF | (ret[6] & 0xFF) << 8);
    		this.Programmed_Bolus_Extended_Amount = (float)ToValue( s2 );

    		this.Programmed_Bolus_Duration = (short)(ret[7] & 0xFF | (ret[8] & 0xFF) << 8);
    		
    		Log.i("kayjean" , "EventType_5A Bolus_ID " + Bolus_ID );
    		Log.i("kayjean" , "EventType_5A Bolus_Type " + Bolus_Type );
    		Log.i("kayjean" , "EventType_5A Programmed_Bolus_Fast_Amount " + Programmed_Bolus_Fast_Amount );
    		Log.i("kayjean" , "EventType_5A Programmed_Bolus_Extended_Amount " + Programmed_Bolus_Extended_Amount );
    		Log.i("kayjean" , "EventType_5A Programmed_Bolus_Duration " + Programmed_Bolus_Duration );
    		
    		return;
    	}
    }

    public class EventType_66{
    	public int getFlags() {
			return Flags;
		}

		public int getBolus_Delay_Time() {
			return Bolus_Delay_Time;
		}

		public int getBolus_Template_Number() {
			return Bolus_Template_Number;
		}

		public int getBolus_Activation_Type() {
			return Bolus_Activation_Type;
		}

		int Flags = 0;
    	int Bolus_Delay_Time = 0;
    	int Bolus_Template_Number = 0;
    	int Bolus_Activation_Type = 0;
    	
    	

/*    	
    Table 3 90<<IDD History Data>>, Bolus Programmed Part 2 of 2, event data definition
    Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order
    Flags	Mandatory	8 bit	1	none	N/A 
    Bolus Delay Time	Attached if bit 0 of Flags field is set otherwise excluded	uint16	2	minutes	LSO¡KMSO 
    Bolus Template Number	Attached if bit 1 of Flags field is set otherwise excluded	uint8	1	none	N/A 
    Bolus Activation Type	Attached if bit 2 of Flags field is set otherwise excluded	enum of uint8	1	none	N/A 
*/

    	public String encode( int Flags , int Bolus_Delay_Time , int Bolus_Template_Number , int Bolus_Activation_Type  )
    	{
    		this.Flags = Flags;
        	this.Bolus_Delay_Time = Bolus_Delay_Time;
        	this.Bolus_Template_Number = Bolus_Template_Number;
        	this.Bolus_Activation_Type = Bolus_Activation_Type;
    		boolean bit0 = BigInteger.valueOf(this.Flags).testBit(0);    		
    		boolean bit1 = BigInteger.valueOf(this.Flags).testBit(1);
    		boolean bit2 = BigInteger.valueOf(this.Flags).testBit(2);
    		int totallength = 1;
    		if( bit0 == true ) totallength += 2; 
    		if( bit1 == true ) totallength += 1;
    		if( bit2 == true ) totallength += 1;
    		
    		byte[] result = new byte[totallength];
    		int p = 0;
    		result[p] = (byte) ((this.Flags & 0x000000FF) >> 0);

    		if( bit0 == true ){
        		result[p++] = (byte) ((this.Bolus_Delay_Time & 0x000000FF) >> 0);
        		result[p++] = (byte) ((this.Bolus_Delay_Time & 0x0000FF00) >> 8);
    		}
    		if( bit1 == true ){
        		result[p++] = (byte) ((this.Bolus_Template_Number & 0x000000FF) >> 0);
    		}
    		if( bit2 == true ){
        		result[p++] = (byte) ((this.Bolus_Activation_Type & 0x000000FF) >> 0);
    		}
    		decode(getHex( result ));
    		return getHex( result );
    	}

    	public void decode( String s )
    	{
    		Log.i("kayjean" , "EventType_66 decode " + s );
    		byte[] ret = hexStringToByteArray( s );
    		this.Flags = ret[0] & 0xFF;
    		boolean bit0 = BigInteger.valueOf(this.Flags).testBit(0);    		
    		boolean bit1 = BigInteger.valueOf(this.Flags).testBit(1);
    		boolean bit2 = BigInteger.valueOf(this.Flags).testBit(2);

    		int p = 0;
    		if( bit0 == true )
    			this.Bolus_Delay_Time = (short)(ret[p++] & 0xFF | (ret[p++] & 0xFF) << 8);
    		if( bit1 == true )
    			this.Bolus_Template_Number = ret[p++] & 0xFF;
    		if( bit2 == true )
    			this.Bolus_Activation_Type = ret[p++] & 0xFF;
    		
    		Log.i("kayjean" , "EventType_66 Flags " + Flags );
    		Log.i("kayjean" , "EventType_66 Bolus_Delay_Time " + Bolus_Delay_Time );
    		Log.i("kayjean" , "EventType_66 Bolus_Template_Number " + Bolus_Template_Number );
    		Log.i("kayjean" , "EventType_66 Bolus_Activation_Type " + Bolus_Activation_Type );
    		
    		return;
    	}
    }
    
    /*
    69
    Table 3 91<<IDD History Data>>, Bolus Delivered Part 1 of 2, event data definition
    Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order
    Bolus ID	M	uint16	2	none	LSO¡KMSO 
    Bolus Type	M	enum of uint8	1	none	N/A 
    Delivered Bolus Fast Amount	M	SFLOAT	2	IU	LSO¡KMSO 
    Delivered Bolus Extended Amount	M	SFLOAT	2	IU	LSO¡KMSO 
    Effective Bolus Duration	M	uint16	2	minutes	LSO¡KMSO 
        
     */

        public class EventType_69{
        	public int getBolus_ID() {
				return Bolus_ID;
			}

			public int getBolus_Type() {
				return Bolus_Type;
			}

			public float getDelivered_Bolus_Fast_Amount() {
				return Delivered_Bolus_Fast_Amount;
			}

			public float getDelivered_Bolus_Extended_Amount() {
				return Delivered_Bolus_Extended_Amount;
			}

			public int getEffective_Bolus_Duration() {
				return Effective_Bolus_Duration;
			}

			int Bolus_ID= 0;
        	int Bolus_Type= 0;
        	float Delivered_Bolus_Fast_Amount = 0;
        	float Delivered_Bolus_Extended_Amount = 0;
        	int Effective_Bolus_Duration = 0;
        	
        	public String encode(int Bolus_ID , int Bolus_Type , float Delivered_Bolus_Fast_Amount , float Delivered_Bolus_Extended_Amount , int Effective_Bolus_Duration)
        	{
        		this.Bolus_ID = Bolus_ID;
            	this.Bolus_Type = Bolus_Type;
            	this.Delivered_Bolus_Fast_Amount = Delivered_Bolus_Fast_Amount;
            	this.Delivered_Bolus_Extended_Amount = Delivered_Bolus_Extended_Amount;
            	this.Effective_Bolus_Duration = Effective_Bolus_Duration;
        		byte[] result = new byte[9];
        		result[0] = (byte) ((Bolus_ID & 0x000000FF) >> 0);
        		result[1] = (byte) ((Bolus_ID & 0x0000FF00) >> 8);
        		
        		result[2] = (byte) ((Bolus_Type & 0x000000FF) >> 0);

        		short s1 = ToSFloat( (double)Delivered_Bolus_Fast_Amount );
        		result[4] = (byte)((s1 >> 8) & 0xff);
        		result[3] = (byte)(s1 & 0xff);    		

        		short s2 = ToSFloat( (double)Delivered_Bolus_Extended_Amount );
        		result[6] = (byte)((s2 >> 8) & 0xff);
        		result[5] = (byte)(s2 & 0xff);
        		
        		result[8] = (byte) ((Effective_Bolus_Duration & 0x0000FF00) >> 8);
        		result[7] = (byte) ((Effective_Bolus_Duration & 0x000000FF) >> 0);
        		decode(getHex( result ));
        		return getHex( result );
        	}

        	public void decode( String s )
        	{
        		Log.i("kayjean" , "EventType_69 decode " + s );
        		byte[] ret = hexStringToByteArray( s );
        		this.Bolus_ID = ret[0] & 0xFF | (ret[1] & 0xFF) << 8;
        		this.Bolus_Type = ret[2] & 0xFF;
        		
        		short s1 = (short)(ret[3] & 0xFF | (ret[4] & 0xFF) << 8);
        		this.Delivered_Bolus_Fast_Amount = (float)ToValue( s1 );

        		short s2 = (short)(ret[5] & 0xFF | (ret[6] & 0xFF) << 8);
        		this.Delivered_Bolus_Extended_Amount = (float)ToValue( s2 );

        		this.Effective_Bolus_Duration = (short)(ret[7] & 0xFF | (ret[8] & 0xFF) << 8);
        		
        		Log.i("kayjean" , "EventType_69 Bolus_ID " + Bolus_ID );
        		Log.i("kayjean" , "EventType_69 Bolus_Type " + Bolus_Type );
        		Log.i("kayjean" , "EventType_69 Delivered_Bolus_Fast_Amount " + Delivered_Bolus_Fast_Amount );
        		Log.i("kayjean" , "EventType_69 Delivered_Bolus_Extended_Amount " + Delivered_Bolus_Extended_Amount );
        		Log.i("kayjean" , "EventType_69 Effective_Bolus_Duration " + Effective_Bolus_Duration );
        		
        		return;
        	}
        }
    
/*
96
Table 3 92<<IDD History Data>>, Bolus Delivered Part 2 of 2, event data definition
Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order
Flags	Mandatory	8 bit	1	none	N/A 
Bolus Start Time Offset	Mandatory	uint32	4		LSO¡KMSO 
Bolus Activation Type	Attached if bit 0 of Flags field is set otherwise excluded	enum of uint8	1	none	N/A 

 */
        
        public class EventType_96{
        	public int getFlags() {
				return Flags;
			}

			public int getBolus_Start_Time_Offset() {
				return Bolus_Start_Time_Offset;
			}

			public int getBolus_Activation_Type() {
				return Bolus_Activation_Type;
			}

			int Flags = 0;
        	int Bolus_Start_Time_Offset = 0;
        	int Bolus_Activation_Type = 0;

        	public String encode(int Flags , int Bolus_Start_Time_Offset , int Bolus_Activation_Type)
        	{
        		this.Flags = Flags;
            	this.Bolus_Start_Time_Offset = Bolus_Start_Time_Offset;
            	this.Bolus_Activation_Type = Bolus_Activation_Type;
        		byte[] result = new byte[9];
        		result[0] = (byte) ((Flags & 0x000000FF) >> 0);
        		
        		result[1] = (byte) ((Bolus_Start_Time_Offset & 0x000000FF) >> 0);
        		result[2] = (byte) ((Bolus_Start_Time_Offset & 0x0000FF00) >> 8);
        		result[3] = (byte) ((Bolus_Start_Time_Offset & 0x00FF0000) >> 16);
        		result[4] = (byte) ((Bolus_Start_Time_Offset & 0xFF000000) >> 24);
        		
        		result[5] = (byte) ((Bolus_Activation_Type & 0x000000FF) >> 0);
        		decode(getHex( result ));
        		return getHex( result );
        	}

        	public void decode( String s )
        	{
        		Log.i("kayjean" , "EventType_96 decode " + s );
        		byte[] ret = hexStringToByteArray( s );
        		this.Flags = ret[0] & 0xFF;

        		this.Bolus_Start_Time_Offset = 
        				ret[1] & 0xFF | 
        				(ret[2] & 0xFF) << 8 |
        				(ret[3] & 0xFF) << 16 |
        				(ret[4] & 0xFF) << 24
        				;
        		
        		this.Bolus_Activation_Type = ret[5] & 0xFF;
        		
        		Log.i("kayjean" , "EventType_96 Flags " + Flags );
        		Log.i("kayjean" , "EventType_96 Bolus_Start_Time_Offset " + Bolus_Start_Time_Offset );
        		Log.i("kayjean" , "EventType_96 Bolus_Activation_Type " + Bolus_Activation_Type );
        		
        		return;
        	}
        }
    
/*
30C
Table 3 106<<IDD History Data>>, Operational State Changed, event data definition
Fields	Conditional Requirements	Data Type	Size (octets)	Unit	Byte Order
Operational State	Mandatory	enum of uint8	1	none	N/A 
       
 */
        
        public class EventType_30C{
        	public int getOperational_State() {
				return Operational_State;
			}

			int Operational_State = 0;

        	public String encode(int Operational_State)
        	{
        		this.Operational_State = Operational_State;
        		byte[] result = new byte[1];
        		result[0] = (byte) ((Operational_State & 0x000000FF) >> 0);
        		decode(getHex( result ));
        		return getHex( result );
        	}

        	public void decode( String s )
        	{
        		Log.i("kayjean" , "EventType_30C decode " + s );
        		byte[] ret = hexStringToByteArray( s );
        		this.Operational_State = ret[0] & 0xFF;
        		
        		Log.i("kayjean" , "EventType_30C Operational_State " + Operational_State );
        		
        		return;
        	}
        }


        
        
        
        
    public byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                                 + Character.digit(s.charAt(i+1), 16));
        }
        return data;
    }

    
    
    
    public String getHex( byte [] raw ) {
    	String HEXES = "0123456789ABCDEF";
        if ( raw == null ) {
            return null;
        }
        final StringBuilder hex = new StringBuilder( 2 * raw.length );
        for ( final byte b : raw ) {
            hex.append(HEXES.charAt((b & 0xF0) >> 4))
                .append(HEXES.charAt((b & 0x0F)));
        }
        return hex.toString();
    }
    
    public short NAN = 0x07FF;
    public short NRES = 0x0800;
    public short POSITIVE_INFINITY = 0x07FE;
    public short NEGATIVE_INFINITY = 0x0802;
    public short RESERVED = 0x0801;
	
    public short ToSFloat(double value)
    {
        int exponent = 0;
        int mantissa = 0;

        boolean bNegative;

        if (value < 0)
        {
            value = -value;
            bNegative = true;
        }
        else
        {
            bNegative = false;
        }

        while (Math.floor(value) != value)
        {
            double tmp = value * 10.0;

            if (tmp < POSITIVE_INFINITY && exponent != -8)
            {
                value = tmp;
                --exponent;
            }
            else
            {
                break;
            }
        }

        while (POSITIVE_INFINITY <= value && exponent != 7)
        {
            value /= 10.0;
            ++exponent;
        }

        if (bNegative)
        {
            mantissa = (int)(-value - 0.5) & 0x0FFF;
        }
        else
        {
            mantissa = (int)(value + 0.5) & 0x0FFF;
        }

        if (POSITIVE_INFINITY <= value)
        {
            if (bNegative)
            {
                return NEGATIVE_INFINITY;
            }
            else
            {
                return POSITIVE_INFINITY;
            }
        }
        else if (exponent != -8 || mantissa != 0)
        {
            return (short)(((exponent & 0x0F) << 12) | mantissa);
        }
        else
        {
            return 0;
        }
    }
    
    public double ToValue(short value)
    {
        int mantissa = value & 0x0FFF;
        int exponent = (value >> 12) & 0x0F;

        if (2047 < mantissa)
        {
            mantissa = (mantissa & 0x07FF) - 2048;
        }

        if (7 < exponent)
        {
            exponent = (exponent & 0x07) - 8;
        }

        return mantissa * Math.pow(10.0, exponent);
    }
    
    
}


/*
0x005A	Bolus Programmed Part 1 of 2 
0x0066	Bolus Programmed Part 2 of 2 
0x0069	Bolus Delivered Part 1 of 2 
0x0096	Bolus Delivered Part 2 of 2 
0x0099	Delivered Basal Rate Changed
0x00A5	TBR Adjustment Started
0x00AA	TBR Adjustment Ended
0x00C3	TBR Adjustment Changed
0x00CC	Basal Rate Profile Activated
0x00F0	Basal Rate Profile Time Block Changed
0x00FF	Total Daily Insulin Delivery
0x0303	Therapy Control State Changed
0x030C	Operational State Changed
0x0330	Reservoir Remaining Amount Changed
0x033F	Annunciation Status Changed Part 1 of 2 
0x0356	Annunciation Status Changed Part 2 of 2 
0x036A	Priming Started 
0x0395	Priming Done 
0x039A	Data Corruption
0x03A7¡V 0xEEEE	RFU
0xF000	Change Reservoir
0xF00F	Programming of a Quick Bolus
0xF033	Abort Programming Of a Quick Bolus
0xF03C	Quick Bolus Amount Limit
0xF055	Temperature Measurement
0xF05A	Last Power Cell Voltage
0xF066	Power Up 
0xF069	Power Down 
0xF096	Bluetooth Bonding 
0xF099	Bluetooth Connect 
0xF0A5	Bluetooth Disconnect 
0xF0AA	Bluetooth On Off 
0xF0C3	Config Block 1 Set Part 1 of 2
0xF0CC	Config Block 1 Set Part 2 of 2
0xF0F0	Config Block 2 Set
0xF0FF	Generic
0xF303	E7 Part 1 of 4
0xF330	E7 Part 2 of 4
0xF33F	E7 Part 3 of 4
0xF356	E7 Part 4 of 4
0xF303 ¡V 0xFFF0	RFU Manufacturer Specific Values

*/
