/** 
 * ===========================================================================
 * Copyright 2015 Roche Diagnostics GmbH
 * All Rights Reserved
 * ===========================================================================
 *
 * Class name: ReminderBGAfterHighTable
 * Brief: 
 *
 * Create Date: 11/19/2015
 * $Revision: $
 * $Author: $
 * $Id: $
 */

package com.accu_chek.solo_m.rcapp.application.reminder;

import java.util.ArrayList;

import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;

import com.accu_chek.solo_m.rcapp.application.safety.CRCTool;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyChannel;
import com.accu_chek.solo_m.rcapp.application.safety.SafetyString;
import com.accu_chek.solo_m.rcapp.application.util.CommonUtils;
import com.accu_chek.solo_m.rcapp.data.nugendata.DBHelper;
import com.accu_chek.solo_m.rcapp.data.nugendata.DatabaseUtil;
import com.accu_chek.solo_m.rcapp.data.operationhandler.AbstractReminderTable;
import com.accu_chek.solo_m.rcapp.data.operationhandler.IDBData;

public class ReminderBGAfterHighTable extends AbstractReminderTable
{

    // Table column name. This column value will be generated automatically by
    // Android.
    public static final String COLUMN_RECORD_ID = "record_id";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_STATE = "reminder_state";
    
    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_BG_THRESHOLD = "bg_threshold";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_REMIND_AFTER = "remind_after";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TONE = "reminder_tone";

    // The ID of the current queried record generated by Android.
    private int mRecordId = -1;
    
    // Table column value encoded in JSON string type. Original type is Hamming value.
    private String mState = null;
    
    // Table column value encoded in JSON string type. Original type is integer value.
    private String mBGThreshold = null;

    // Table column value encoded in JSON string type. Original type is integer value.
    private String mRemindAfterTime = null;
    
    // Table column value encoded in SafetyString type.
    private String mTone = null;

    // Table column value encoded in JSON string type. Original type is integer value.
    private String mAlarmRequestCode = null;

    
    @Override
    public SafetyChannel<Integer> getRecordId()
    {
        SafetyChannel<Integer> channel = CommonUtils
                .getSafetyChannel(mRecordId);
        
        return channel;
    }
    
    @Override
    public SafetyChannel<Integer> getState()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mState);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }

    @Override
    public SafetyChannel<Integer> getBGThreshold()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mBGThreshold);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);

        return channel;
    }

    @Override
    public SafetyChannel<Integer> getRemindAfterMinute()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mRemindAfterTime);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);

        return channel;
    }
    
    @Override
    public SafetyString getTone()
    {
        SafetyString value = new SafetyString();
        value.set(mTone, CRCTool.generateCRC16(mTone.getBytes()));

        return value;
    }

    @Override
    public SafetyChannel<Integer> getAlarmRequestCode()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mAlarmRequestCode);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }

    /**
     * 
     *
     * @param values
     */

    @Override
    protected void getDataFromContentValue(ContentValues values)
    {
        CommonUtils.objectCheck(values);

        mState = DatabaseUtil.getStringValue(values, COLUMN_STATE, mState);
        mBGThreshold = DatabaseUtil.getStringValue(values, COLUMN_BG_THRESHOLD, mBGThreshold);
        mRemindAfterTime = DatabaseUtil.getStringValue(values, COLUMN_REMIND_AFTER,
                mRemindAfterTime);
        mTone = DatabaseUtil.getStringValue(values, COLUMN_TONE,
                mTone);
        mAlarmRequestCode = DatabaseUtil.getStringValue(values,
                COLUMN_ALARM_REQUEST_CODE, mAlarmRequestCode);
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public Uri onUri()
    {
        return UrlType.reminderBGAfterHighUri;
    }

    /**
     * 
     *
     * @param cursor
     * @return
     */

    @Override
    public IDBData onQueryDataFromCursor(Cursor cursor)
    {
        ReminderBGAfterHighTable model = null;
        
        CommonUtils.objectCheck(cursor);
        
        int recordIdIndex = cursor.getColumnIndex(COLUMN_RECORD_ID);
        int stateIndex = cursor.getColumnIndex(COLUMN_STATE);
        int bgThresholdIndex = cursor.getColumnIndex(COLUMN_BG_THRESHOLD);
        int remindAfterIndex = cursor.getColumnIndex(COLUMN_REMIND_AFTER);
        int toneIndex = cursor.getColumnIndex(COLUMN_TONE);
        int requestCodeIndex = cursor.getColumnIndex(COLUMN_ALARM_REQUEST_CODE);
        int crcIndex = cursor.getColumnIndex(COLUMN_CRC);

        model = new ReminderBGAfterHighTable();

        model.mRecordId = cursor.getInt(recordIdIndex);
        model.mState = DatabaseUtil.getStringValue(cursor, stateIndex);
        model.mBGThreshold = DatabaseUtil.getStringValue(cursor, bgThresholdIndex);
        model.mRemindAfterTime = DatabaseUtil.getStringValue(cursor, remindAfterIndex);
        model.mTone = DatabaseUtil.getStringValue(cursor, toneIndex);
        model.mAlarmRequestCode = DatabaseUtil.getStringValue(cursor, requestCodeIndex);
        model.setCRC(DatabaseUtil.getIntValue(cursor, crcIndex));
        
        return model;
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public int generateCRC()
    {
        int nCRC = -1;
        ArrayList<String> list = new ArrayList<String>();

        list.add(mState);
        list.add(mBGThreshold);
        list.add(mRemindAfterTime);
        list.add(mTone);
        list.add(mAlarmRequestCode);

        nCRC = DatabaseUtil.generateCRC(list);

        return nCRC;
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public String getPrimaryKeyName()
    {
        return ReminderBGAfterHighTable.COLUMN_RECORD_ID;
    }
    
    @Override
    protected String getTableName()
    {
        return DBHelper.REMINDER_BG_AFTER_HIGH_TABLE;
    }

}

/*
 * ===========================================================================
 *
 * Revision history
 *  
 * ===========================================================================
 */
// [Reminder] 1. add bG after high / low / meal reminders
// 2. add doctor visit and lab test reminders
