/** 
 * ===========================================================================
 * Copyright 2015 Roche Diagnostics GmbH
 * All Rights Reserved
 * ===========================================================================
 *
 * Class name: ReminderAlarmListTable
 * Brief: 
 *
 * Create Date: 11/26/2015
 * $Revision: $
 * $Author: $
 * $Id: $
 */

package com.accu_chek.solo_m.rcapp.application.reminder;

import java.util.ArrayList;

import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;

import com.accu_chek.solo_m.rcapp.application.safety.SafetyChannel;
import com.accu_chek.solo_m.rcapp.application.util.CommonUtils;
import com.accu_chek.solo_m.rcapp.data.nugendata.DBHelper;
import com.accu_chek.solo_m.rcapp.data.nugendata.DatabaseUtil;
import com.accu_chek.solo_m.rcapp.data.operationhandler.AbstractTable;
import com.accu_chek.solo_m.rcapp.data.operationhandler.IDBData;

public class ReminderAlarmListTable extends AbstractTable
{

    // Table column name. This column value will be generated automatically by
    // Android.
    public static final String COLUMN_RECORD_ID = "record_id";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_TIME = "alarm_time";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_REPEAT_STATUS = "alarm_repeat_status";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_EMWR_CODE = "emwr_code";

    // Table column name. This column value must not be null when inserting or
    // an SQLiteException will occur.
    public static final String COLUMN_ALARM_REQUEST_CODE = "alarm_request_code";


    // The ID of the current queried record generated by Android.
    private int mRecordId = -1;
    
    // Table column value encoded in SafetyString type. 
    private String mTime = null;
    
    // Table column value encoded in JSON string type. Original type is Hamming value.
    private String mRepeatStatus = null;

    // Table column value encoded in JSON string type. Original type is Hamming value.
    private String mEMWRCode = null;

    // Table column value encoded in JSON string type. Original type is integer value.
    private String mAlarmRequestCode = null;

    
    public SafetyChannel<Integer> getRecordId()
    {
        SafetyChannel<Integer> channel = CommonUtils
                .getSafetyChannel(mRecordId);
        
        return channel;
    }

    public SafetyChannel<Long> getTime()
    {
        long[] channelValue = DatabaseUtil.restoreChannelLongValue(mTime);
        SafetyChannel<Long> channel = new SafetyChannel<Long>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }


    public SafetyChannel<Integer> getRepeatStatus()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mRepeatStatus);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }

    public SafetyChannel<Integer> getEMWRCode()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mEMWRCode);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }

    public SafetyChannel<Integer> getAlarmRequestCode()
    {
        int[] channelValue = DatabaseUtil.restoreChannelIntValue(mAlarmRequestCode);
        SafetyChannel<Integer> channel = new SafetyChannel<Integer>(
                channelValue[0], channelValue[1]);
        
        return channel;
    }

    /**
     * 
     *
     * @param values
     */

    @Override
    protected void getDataFromContentValue(ContentValues values)
    {
        CommonUtils.objectCheck(values);

        mTime = DatabaseUtil.getStringValue(values, COLUMN_TIME,
                mTime);
        mRepeatStatus = DatabaseUtil.getStringValue(values, 
                COLUMN_REPEAT_STATUS, mRepeatStatus);
        mEMWRCode = DatabaseUtil.getStringValue(values, 
                COLUMN_EMWR_CODE, mEMWRCode);
        mAlarmRequestCode = DatabaseUtil.getStringValue(values,
                COLUMN_ALARM_REQUEST_CODE, mAlarmRequestCode);
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public Uri onUri()
    {
        return UrlType.reminderAlarmListUri;
    }

    /**
     * 
     *
     * @param cursor
     * @return
     */

    @Override
    public IDBData onQueryDataFromCursor(Cursor cursor)
    {
        ReminderAlarmListTable model = null;
        
        CommonUtils.objectCheck(cursor);
        
        int recordIdIndex = cursor.getColumnIndex(COLUMN_RECORD_ID);
        int timeIndex = cursor.getColumnIndex(COLUMN_TIME);
        int repeatStatusIndex = cursor.getColumnIndex(COLUMN_REPEAT_STATUS);
        int emwrCodeIndex = cursor.getColumnIndex(COLUMN_EMWR_CODE);
        int requestCodeIndex = cursor.getColumnIndex(COLUMN_ALARM_REQUEST_CODE);
        int crcIndex = cursor.getColumnIndex(COLUMN_CRC);

        model = new ReminderAlarmListTable();

        model.mRecordId = cursor.getInt(recordIdIndex);
        model.mTime = DatabaseUtil.getStringValue(cursor, timeIndex);
        model.mRepeatStatus = DatabaseUtil.getStringValue(cursor, repeatStatusIndex);
        model.mEMWRCode = DatabaseUtil.getStringValue(cursor, emwrCodeIndex);
        model.mAlarmRequestCode = DatabaseUtil.getStringValue(cursor, requestCodeIndex);
        model.setCRC(DatabaseUtil.getIntValue(cursor, crcIndex));
        
        return model;
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public int generateCRC()
    {
        int nCRC = -1;
        ArrayList<String> list = new ArrayList<String>();

        list.add(mTime);
        list.add(mRepeatStatus);
        list.add(mEMWRCode);
        list.add(mAlarmRequestCode);

        nCRC = DatabaseUtil.generateCRC(list);

        return nCRC;
    }

    /**
     * 
     *
     * @return
     */

    @Override
    public String getPrimaryKeyName()
    {
        return ReminderAlarmListTable.COLUMN_RECORD_ID;
    }
    
    @Override
    protected String getTableName()
    {
        return DBHelper.REMINDER_ALARM_LIST_TABLE;
    }

}

/*
 * ===========================================================================
 *
 * Revision history
 *  
 * ===========================================================================
 */
// [Reminder] update Reminder module
// [Reminder] update Reminder module
// [Reminder] update Reminder module
